language: python

sudo: required

python:
  - "2.7"

jdk:
  - oraclejdk7

install:

  # install custom tomcat7
  - sudo unzip tests/vendor/tomcat7.zip -d /

  # install GeoServer
  - wget http://sourceforge.net/projects/geoserver/files/GeoServer/2.7.2/geoserver-2.7.2-war.zip
  - unzip geoserver-2.7.2-war.zip geoserver.war
  - sudo cp geoserver.war /tomcat7/webapps/
  - sudo sh /tomcat7/bin/startup.sh

  # install Python packages
  - "pip install -r requirements.txt"
  - "pip install pytest pytest-cov"
  - "pip install -e ."   # install package using setup.py in editable mode

script:
   - py.test --cov geobricks_geoserver_manager.core --cov-report term-missing